### ISSUE TITLE
Maybe a better name

### ISSUE THREAD

**Issue by johnpyp** [fabiospampinato/template#1]
First of all, I think this project is awesome. I saw it on your medium post about vscode-extensions, and I've been looking for something like it for a long time. I used Khaos previously, even after it was inactive for years.

Anyways, the name `template` is very generic, and something more unique would be a better fit (like how Khaos was unique). Easy to remember, easy to search for on google or github, and can fit a unique npm package (unlike the namespaced one you have now).

**Comment by fabiospampinato** [comment]
It's a good point, but I think "template" is actually more appropriate than "khaos", which doesn't tell me anything about the program.

I agree that it's somewhat harder to find on Google, and that publishing it under by namespace is not ideal, but I couldn't find a better name when I created it. If you can come up with a better, descriptive, name I'm all hears. In the meantime I'm closing this issue.

Unfortunately both `template` and `tmpl` are popular packages so an ownership transfer is off the table... actually you'll never know these days 😂
