### ISSUE TITLE
feature I working on.

### ISSUE THREAD

**Issue by frog-o** [fabiospampinato/template#3]
I am trying to make  some built in template to easy project creating and add the ability to  merge and scaffold using templates. I name the first inbuilt template config4.  I trying to create what I call a generator.  The difference between generator and create is generator is use to add code to project where create is use primarily to replace. The main reason generator where made is to handle the problem
    of every program wanting there version of package manager( yarn ,pnpm,npm), Until this feature is add , you would keep having to put 
    "packageManager": "pnpm@7.2.1" or what ever package manager your want in package.json, delete there lockfiles and other
    annoying things over and over ,this feature attempts to solve all that by just running
    
    template gen config4 defaults

I want generate to do a little more I just thought this might be usful everying still work in progress. But i would like to hear people thought as i develop,. Especially if you don't want this type of thing that way I know to rename my fork.  I much rather try to work together i feel early feedback is the key to that.

Work that i done so far.

*Rename project to template output because it better reflect what is is asking 4
* Added code to help launch template (your project even though i think it might be better name t-n-t for template and typescript a power full combination.) In vscode. I was going to use TNT; if i have to create drive work with no chance of getting merged back.
* upgrade libraries
* add depending ts-node but allowed for execution.
* create a new launch script in package.json to execute typescript in ts-node.

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, I consider this little CLI app mostly done and I don't intend to spend much time developing it further, but, I'd like eventually to get #2 implemented, which would allow executing arbitrary code for a template also, which would enable more powerful sort of templates, perhaps like the ones you need.
